<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Desktop" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.11"/>
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.11">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1"/>
        <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.2"/>
        <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.2"/>
        <ProjectReference Include="..\EasyLog\EasyLog.csproj"/>
        <ProjectReference Include="..\EasySave.Protocol\EasySave.Protocol.csproj"/>
        <ProjectReference Include="..\EasySave.Translation\EasySave.Translation.csproj"/>
        <None Update="Tools\CryptoSoft.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**"/>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\EditBackupScreen.axaml.cs">
        <DependentUpon>EditBackupScreen.axaml</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
        <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
            <_Parameter1>EasySaveTest</_Parameter1>
        </AssemblyAttribute>
    </ItemGroup>

</Project>
